---
development:
  cloud_name: dnh7ailn8
  api_key: '662417595292451'
  api_secret: dzP3s-ULJVdTuz_Ia-FWOVep5W0
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dnh7ailn8
  api_key: '662417595292451'
  api_secret: dzP3s-ULJVdTuz_Ia-FWOVep5W0
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dnh7ailn8
  api_key: '662417595292451'
  api_secret: dzP3s-ULJVdTuz_Ia-FWOVep5W0
  enhance_image_tag: true
  static_image_support: false
